apiVersion: v1
kind: Namespace
metadata:
  name: trading-guide
  labels:
    name: trading-guide
    environment: production
    app: trading-guide
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: trading-guide-quota
  namespace: trading-guide
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: trading-guide-limits
  namespace: trading-guide
spec:
  limits:
  - max:
      cpu: "2"
      memory: "2Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    default:
      cpu: "200m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
